### ISSUE TITLE
Update for the latest yolov8 version

### ISSUE THREAD

**Issue by AndreiVoian** [BogdanMarghescu/YOLOv8-Object-Detection-and-Image-Segmentation#2]
Hi! Can you update the script to work with the latest version of yolov8?

Thanks!

**Comment by BogdanMarghescu** [comment]
Hi, could you please elaborate? It seems that the code still works with the latest "ultralytics" package on my computer.

**Comment by AndreiVoian** [comment]
When I run the script it gives me this error:

```
Traceback (most recent call last):
  File "C:\Users\Department\Desktop\yolov8\yolov8_seg.py", line 67, in <module>
    image, result_list_json = object_segmentation(image, model, temp_filename='temp.png')
  File "C:\Users\Department\Desktop\yolov8\yolov8_seg.py", line 20, in object_segmentation
    if len(result['segment']) != len(result['det']):
  File "C:\Users\Department\Desktop\yolov8\venv\lib\site-packages\ultralytics\yolo\engine\results.py", line 44, in __getitem__
    setattr(r, item, getattr(self, item)[idx])
  File "C:\Users\Department\Desktop\yolov8\venv\lib\site-packages\ultralytics\yolo\engine\results.py", line 220, in __getitem__
    boxes = self.boxes[idx]
IndexError: too many indices for tensor of dimension 2
```

**Comment by BogdanMarghescu** [comment]
Could you please give me a Wetransfer/Mega.nz/Drive link with your test image, as well as your ultralytics version from python?

**Comment by AndreiVoian** [comment]
I teste on this image:
![dog](https://user-images.githubusercontent.com/122984600/219400628-5ebeebc5-9939-4a47-bccd-255916beee9e.jpg)

Ultralytics version is 8.0.38

**Comment by BogdanMarghescu** [comment]
I tested with this image and i got no such error. My version of ultralytics is 8.0.5, the latest version.

**Comment by AndreiVoian** [comment]
The latest version of ultralytics is 8.0.39

Try to upgrade to the latest version ( pip install ultralytics --upgrade )

**Comment by BogdanMarghescu** [comment]
Indeed, you are correct, my apologies. I shall update my code as soon as possible.

**Comment by BogdanMarghescu** [comment]
The script is updated, now it should work.

**Comment by AndreiVoian** [comment]
Thank you very much!
